<a href="https://colab.research.google.com/github/fmtorou/Colab2/blob/main/Colab_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Some** text here

In [10]:
import torch

In [4]:
import numpy as np

In [5]:
mL = [1,2,3]
mL

[1, 2, 3]

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.03033061, 0.12490664, 0.12665616, 0.00546641],
       [0.55459343, 0.91305159, 0.37721096, 0.36531758],
       [0.60730193, 0.94465996, 0.3664725 , 0.01152052]])

In [8]:
np1.dtype

dtype('float64')

#Tensors




In [11]:
t2d = torch.randn(3,4)
t2d

tensor([[-0.9060,  0.6765, -0.9690, -0.7442],
        [ 0.0733, -1.3071, -0.9105,  0.9659],
        [ 1.8404,  0.1527,  0.2077, -0.5657]])

In [12]:
t3d = torch.zeros(2,3,4)
t3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])